services:
  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    network_mode: host
    pid: host
    environment:
      DATA_SOURCE_URI: 'localhost:5432/postgres?sslmode=disable'
      DATA_SOURCE_USER: ${POSTGRES_USER}
      DATA_SOURCE_PASS: ${POSTGRES_PASSWORD}
    restart: unless-stopped
